import { useEffect, useMemo, useRef, useState } from 'react'
import type { ChangeEvent, DragEvent } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { importClaudeFiles } from './data/import-client'
import { clearAllData, legacyArchiveSnapshot } from './data/db'
import './App.css'

type Block={type:string;text?:string;payload?:unknown}; type Message={id:string;role:string;createdAt?:string;blocks:Block[]}; type Conversation={id:string;title:string;createdAt?:string;updatedAt?:string;messages:Message[]}; type Archive={version:1;importedAt:string;warnings:string[];conversations:Conversation[]}
const textOf=(m:Message)=>m.blocks.map(b=>b.text??'').join('\n'); const date=(v?:string)=>v?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'时间未知'
async function db(action:'get'|'clear'):Promise<Archive|undefined>{if(action==='get')return legacyArchiveSnapshot();await clearAllData();return undefined}
function download(name:string,data:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
export default function App(){const[archive,setArchive]=useState<Archive|null>(null),[page,setPage]=useState('import'),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);useEffect(()=>{db('get').then(a=>{if(a){setArchive(a);setSelected(a.conversations[0]?.id??'');setPage('archive')}})},[]);const conversations=useMemo(()=>archive?.conversations??[],[archive]),current=conversations.find(c=>c.id===selected)??conversations[0];const found=useMemo(()=>conversations.filter(c=>(c.title+'\n'+c.messages.map(textOf).join('\n')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(b.updatedAt??'').localeCompare(a.updatedAt??'')),[conversations,query]);const all=conversations.flatMap(c=>c.messages),chars=all.reduce((n,m)=>n+textOf(m).length,0)
async function importFile(files:File[]){setBusy(true);setNote('正在扫描文件…');try{const session=await importClaudeFiles(files,progress=>setNote(`${progress.phase} ${progress.percent}%`)),a=await legacyArchiveSnapshot();setArchive(a);setSelected(a.conversations[0]?.id??'');setPage('archive');setNote(`导入完成：${a.conversations.length} 个会话；新增 ${session.counts.inserted}，更新 ${session.counts.updated}，未变化 ${session.counts.unchanged}，冲突 ${session.counts.conflicted}。`)}catch(e){setNote(`导入失败：${e instanceof Error?e.message:'未知错误'}`)}finally{setBusy(false)}}
function exportOne(format:string){if(!current)return;const safe=current.title.replace(/[\\/:*?"<>|]/g,'_').slice(0,60),body=current.messages.map(m=>`## ${m.role==='user'?'你':m.role==='assistant'?'Claude':m.role}\n${m.createdAt?`*${date(m.createdAt)}*\n`:''}${textOf(m)}`).join('\n\n');if(format==='json')download(`${safe}.json`,JSON.stringify(current,null,2),'application/json');else if(format==='html')download(`${safe}.html`,`<!doctype html><meta charset="utf-8"><title>${safe}</title><style>body{max-width:860px;margin:40px auto;font:16px/1.7 system-ui;white-space:pre-wrap}</style><h1>${safe.replace(/</g,'&lt;')}</h1>${body.replace(/&/g,'&amp;').replace(/</g,'&lt;')}`,'text/html');else download(`${safe}.${format}`,`# ${current.title}\n\n${body}`,'text/plain;charset=utf-8')}
const file=(e:ChangeEvent<HTMLInputElement>)=>{const files=[...(e.target.files??[])];if(files.length)void importFile(files)};const drop=(e:DragEvent)=>{e.preventDefault();const files=[...e.dataTransfer.files];if(files.length)void importFile(files)};return <main><header><div className="brand">✦ 时光之遗 <small>TIME LEGACY</small></div><nav>{[['import','导入'],['archive','档案'],['analytics','统计'],['export','导出']].map(([p,n])=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}>{n}</button>)}</nav><span className="privacy">● 本地处理，未上传</span></header>{note&&<div className="notice">{note}<button onClick={()=>setNote('')}>×</button></div>}
{page==='import'&&<section className="landing"><p className="eyebrow">PRIVATE CONVERSATION ARCHIVE</p><h1>让过去的对话，<em>重新可阅读。</em></h1><p>导入 Claude 官方导出的 ZIP 或 conversations.json。所有处理都在当前浏览器完成。</p><div className="drop" onDragOver={e=>e.preventDefault()} onDrop={drop} onClick={()=>input.current?.click()}><strong>{busy?'正在处理档案…':'拖入 Claude 导出文件'}</strong><span>或点击选择完整导出 ZIP / 多个批次文件</span><i>✦ 支持 Manifest、批次 ZIP 与 conversations.json</i></div><input ref={input} hidden multiple type="file" accept=".json,.zip" onChange={file}/>{archive&&<button className="secondary" onClick={()=>setPage('archive')}>继续阅读已有档案 →</button>}</section>}
{page==='archive'&&<section className="archive"><aside><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题与对话内容"/><p>{found.length} / {conversations.length} 个会话</p>{found.map(c=><button className={`conversation ${current?.id===c.id?'selected':''}`} onClick={()=>setSelected(c.id)} key={c.id}><b>{c.title}</b><span>{date(c.updatedAt)} · {c.messages.length} 条</span></button>)}</aside><article>{current?<><div className="conversation-head"><div><p className="eyebrow">CONVERSATION</p><h2>{current.title}</h2><span>{date(current.createdAt)} — {date(current.updatedAt)} · {current.messages.length} 条</span></div><button className="secondary" onClick={()=>setPage('export')}>导出此窗口</button></div><div className="messages">{current.messages.map(m=><div className={`message ${m.role}`} key={m.id}><div className="role">{m.role==='user'?'你':m.role==='assistant'?'Claude':m.role}</div><div className="message-content">{m.createdAt&&<time>{date(m.createdAt)}</time>}{m.blocks.map((b,i)=>b.type==='text'?<ReactMarkdown key={i} remarkPlugins={[remarkGfm]}>{b.text}</ReactMarkdown>:b.type==='code'?<pre key={i}><code>{b.text}</code></pre>:<details key={i}><summary>{b.type}（点击展开）</summary><pre>{b.text??JSON.stringify(b.payload,null,2)}</pre></details>)}</div></div>)}</div></>:<div className="empty">请先导入档案。</div>}</article></section>}
{page==='analytics'&&<section className="analytics"><p className="eyebrow">LOCAL ANALYTICS</p><h1>你的对话时间线</h1><div className="metrics">{[['会话',conversations.length],['消息',all.length],['你的消息',all.filter(m=>m.role==='user').length],['Claude 消息',all.filter(m=>m.role==='assistant').length],['正文字符',chars.toLocaleString()],['活跃天数',new Set(all.map(m=>m.createdAt?.slice(0,10)).filter(Boolean)).size]].map(([l,v])=><div className="metric" key={String(l)}><span>{l}</span><strong>{v}</strong></div>)}</div><div className="insights"><div><h3>消息最多的窗口</h3><ol>{[...conversations].sort((a,b)=>b.messages.length-a.messages.length).slice(0,5).map(c=><li key={c.id}><button onClick={()=>{setSelected(c.id);setPage('archive')}}>{c.title}</button><span>{c.messages.length} 条</span></li>)}</ol></div></div></section>}
{page==='export'&&<section className="export"><p className="eyebrow">EXPORT</p><h1>带走你的档案</h1>{current?<><p>当前窗口：<b>{current.title}</b>。内容只在本地生成下载。</p><div className="format-grid">{[['md','长期归档，保留角色和代码'],['txt','纯文本，角色分隔清晰'],['html','离线阅读的单文件'],['json','标准化数据，便于二次开发']].map(([f,d])=><button key={f} onClick={()=>exportOne(f)}><strong>{f.toUpperCase()}</strong><span>{d}</span></button>)}</div><hr/><button className="danger" onClick={async()=>{if(confirm('这会从当前浏览器彻底清空聊天正文，确定吗？')){await db('clear');setArchive(null);setSelected('');setPage('import');setNote('本地档案已彻底清空。')}}}>彻底清空本地档案</button></>:<p>请先导入档案。</p>}</section>}</main>}
