import { useEffect, useMemo, useRef, useState } from 'react'
import type { ChangeEvent, DragEvent } from 'react'
import { strFromU8, unzipSync } from 'fflate'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import './App.css'

type Block={type:string;text?:string;payload?:unknown}; type Message={id:string;role:string;createdAt?:string;blocks:Block[]}; type Conversation={id:string;title:string;createdAt?:string;updatedAt?:string;messages:Message[]}; type Archive={version:1;importedAt:string;warnings:string[];conversations:Conversation[]}
const DB='time-legacy', KEY='archive-v1'; const textOf=(m:Message)=>m.blocks.map(b=>b.text??'').join('\n'); const date=(v?:string)=>v?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'时间未知'; const iso=(v:unknown)=>{const d=new Date(String(v));return v&&!Number.isNaN(+d)?d.toISOString():undefined}
const array=(v:unknown)=>Array.isArray(v)?v:[]
function blocks(content:unknown):Block[]{if(typeof content==='string')return content?[{type:'text',text:content}]:[];if(content&&typeof content==='object'&&!Array.isArray(content))return blocks([content]);return array(content).map(x=>{if(typeof x==='string')return{type:'text',text:x};const b=(x??{}) as Record<string,unknown>,t=String(b.type??b.kind??'unknown');if(t==='text'||typeof b.text==='string')return{type:'text',text:String(b.text??'')};if(t==='thinking')return{type:'thinking',text:String(b.thinking??b.text??'')};if(t==='code')return{type:'code',text:String(b.code??b.text??'')};return{type:t,payload:x,text:typeof b.text==='string'?b.text:undefined}})}
function normalize(raw:unknown){const root=raw as Record<string,unknown>,warnings:string[]=[];const list=Array.isArray(raw)?raw:array(root.conversations??root.data??root.items);const conversations=list.map((x,ci)=>{const c=(x??{})as Record<string,unknown>, map=c.mapping as Record<string,unknown>|undefined;const messages=array(c.messages??c.chat_messages??(map?Object.values(map):[])).map((x,mi)=>{const e=(x??{})as Record<string,unknown>,m=(e.message??e)as Record<string,unknown>, author=m.author as Record<string,unknown>|undefined;let role=String(m.sender??m.role??author?.role??'unknown').toLowerCase();if(role==='human')role='user';const result=blocks(m.content??m.text);if(!result.length)warnings.push(`会话 ${ci+1} 的消息 ${mi+1} 未识别`);return{id:String(m.uuid??m.id??e.id??`m-${ci}-${mi}`),role,createdAt:iso(m.created_at??m.createdAt??m.timestamp),blocks:result.length?result:[{type:'unknown',payload:m.content}]}});return{id:String(c.uuid??c.id??`c-${ci}`),title:String(c.name??c.title??`未命名对话 ${ci+1}`),createdAt:iso(c.created_at??c.createdAt),updatedAt:iso(c.updated_at??c.updatedAt??c.created_at),messages}}).filter(c=>c.messages.length);if(!conversations.length)throw Error('未找到可识别的会话。请确认文件是 Claude 官方 conversations.json。');return{conversations,warnings}}
async function db(action:'get'|'put'|'clear',value?:Archive):Promise<Archive|undefined>{const d=await new Promise<IDBDatabase>((ok,bad)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('archives');r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)});const out=await new Promise<Archive|undefined>((ok,bad)=>{const t=d.transaction('archives',action==='get'?'readonly':'readwrite'),s=t.objectStore('archives');if(action==='get'){const r=s.get(KEY);r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)}else{if(action==='put')s.put(value,KEY);else s.clear();t.oncomplete=()=>ok(undefined);t.onerror=()=>bad(t.error)}});d.close();return out}
function download(name:string,data:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
export default function App(){const[archive,setArchive]=useState<Archive|null>(null),[page,setPage]=useState('import'),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);useEffect(()=>{db('get').then(a=>{if(a){setArchive(a);setSelected(a.conversations[0]?.id??'');setPage('archive')}})},[]);const conversations=useMemo(()=>archive?.conversations??[],[archive]),current=conversations.find(c=>c.id===selected)??conversations[0];const found=useMemo(()=>conversations.filter(c=>(c.title+'\n'+c.messages.map(textOf).join('\n')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(b.updatedAt??'').localeCompare(a.updatedAt??'')),[conversations,query]);const all=conversations.flatMap(c=>c.messages),chars=all.reduce((n,m)=>n+textOf(m).length,0)
async function importFile(file:File){setBusy(true);setNote('正在本地解析与保存…');try{let source=await file.text();if(file.name.toLowerCase().endsWith('.zip')){const z=unzipSync(new Uint8Array(await file.arrayBuffer())),key=Object.keys(z).find(k=>/(^|\/)conversations\.json$/i.test(k));if(!key)throw Error('未在导出包中找到 conversations.json');source=strFromU8(z[key])}const n=normalize(JSON.parse(source)),a:Archive={version:1,importedAt:new Date().toISOString(),...n};await db('put',a);setArchive(a);setSelected(a.conversations[0].id);setPage('archive');setNote(`导入完成：${a.conversations.length} 个会话，${a.warnings.length} 条兼容性提醒。`)}catch(e){setNote(`导入失败：${e instanceof Error?e.message:'未知错误'}`)}finally{setBusy(false)}}
function exportOne(format:string){if(!current)return;const safe=current.title.replace(/[\\/:*?"<>|]/g,'_').slice(0,60),body=current.messages.map(m=>`## ${m.role==='user'?'你':m.role==='assistant'?'Claude':m.role}\n${m.createdAt?`*${date(m.createdAt)}*\n`:''}${textOf(m)}`).join('\n\n');if(format==='json')download(`${safe}.json`,JSON.stringify(current,null,2),'application/json');else if(format==='html')download(`${safe}.html`,`<!doctype html><meta charset="utf-8"><title>${safe}</title><style>body{max-width:860px;margin:40px auto;font:16px/1.7 system-ui;white-space:pre-wrap}</style><h1>${safe.replace(/</g,'&lt;')}</h1>${body.replace(/&/g,'&amp;').replace(/</g,'&lt;')}`,'text/html');else download(`${safe}.${format}`,`# ${current.title}\n\n${body}`,'text/plain;charset=utf-8')}
const file=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)void importFile(f)};const drop=(e:DragEvent)=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)void importFile(f)};return <main><header><div className="brand">✦ 时光之遗 <small>TIME LEGACY</small></div><nav>{[['import','导入'],['archive','档案'],['analytics','统计'],['export','导出']].map(([p,n])=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}>{n}</button>)}</nav><span className="privacy">● 本地处理，未上传</span></header>{note&&<div className="notice">{note}<button onClick={()=>setNote('')}>×</button></div>}
{page==='import'&&<section className="landing"><p className="eyebrow">PRIVATE CONVERSATION ARCHIVE</p><h1>让过去的对话，<em>重新可阅读。</em></h1><p>导入 Claude 官方导出的 ZIP 或 conversations.json。所有处理都在当前浏览器完成。</p><div className="drop" onDragOver={e=>e.preventDefault()} onDrop={drop} onClick={()=>input.current?.click()}><strong>{busy?'正在处理档案…':'拖入 Claude 导出文件'}</strong><span>或点击选择 conversations.json / ZIP</span><i>✦ 支持 ZIP 自动查找 conversations.json</i></div><input ref={input} hidden type="file" accept=".json,.zip" onChange={file}/>{archive&&<button className="secondary" onClick={()=>setPage('archive')}>继续阅读已有档案 →</button>}</section>}
{page==='archive'&&<section className="archive"><aside><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题与对话内容"/><p>{found.length} / {conversations.length} 个会话</p>{found.map(c=><button className={`conversation ${current?.id===c.id?'selected':''}`} onClick={()=>setSelected(c.id)} key={c.id}><b>{c.title}</b><span>{date(c.updatedAt)} · {c.messages.length} 条</span></button>)}</aside><article>{current?<><div className="conversation-head"><div><p className="eyebrow">CONVERSATION</p><h2>{current.title}</h2><span>{date(current.createdAt)} — {date(current.updatedAt)} · {current.messages.length} 条</span></div><button className="secondary" onClick={()=>setPage('export')}>导出此窗口</button></div><div className="messages">{current.messages.map(m=><div className={`message ${m.role}`} key={m.id}><div className="role">{m.role==='user'?'你':m.role==='assistant'?'Claude':m.role}</div><div className="message-content">{m.createdAt&&<time>{date(m.createdAt)}</time>}{m.blocks.map((b,i)=>b.type==='text'?<ReactMarkdown key={i} remarkPlugins={[remarkGfm]}>{b.text}</ReactMarkdown>:b.type==='code'?<pre key={i}><code>{b.text}</code></pre>:<details key={i}><summary>{b.type}（点击展开）</summary><pre>{b.text??JSON.stringify(b.payload,null,2)}</pre></details>)}</div></div>)}</div></>:<div className="empty">请先导入档案。</div>}</article></section>}
{page==='analytics'&&<section className="analytics"><p className="eyebrow">LOCAL ANALYTICS</p><h1>你的对话时间线</h1><div className="metrics">{[['会话',conversations.length],['消息',all.length],['你的消息',all.filter(m=>m.role==='user').length],['Claude 消息',all.filter(m=>m.role==='assistant').length],['正文字符',chars.toLocaleString()],['活跃天数',new Set(all.map(m=>m.createdAt?.slice(0,10)).filter(Boolean)).size]].map(([l,v])=><div className="metric" key={String(l)}><span>{l}</span><strong>{v}</strong></div>)}</div><div className="insights"><div><h3>消息最多的窗口</h3><ol>{[...conversations].sort((a,b)=>b.messages.length-a.messages.length).slice(0,5).map(c=><li key={c.id}><button onClick={()=>{setSelected(c.id);setPage('archive')}}>{c.title}</button><span>{c.messages.length} 条</span></li>)}</ol></div></div></section>}
{page==='export'&&<section className="export"><p className="eyebrow">EXPORT</p><h1>带走你的档案</h1>{current?<><p>当前窗口：<b>{current.title}</b>。内容只在本地生成下载。</p><div className="format-grid">{[['md','长期归档，保留角色和代码'],['txt','纯文本，角色分隔清晰'],['html','离线阅读的单文件'],['json','标准化数据，便于二次开发']].map(([f,d])=><button key={f} onClick={()=>exportOne(f)}><strong>{f.toUpperCase()}</strong><span>{d}</span></button>)}</div><hr/><button className="danger" onClick={async()=>{if(confirm('这会从当前浏览器彻底清空聊天正文，确定吗？')){await db('clear');setArchive(null);setSelected('');setPage('import');setNote('本地档案已彻底清空。')}}}>彻底清空本地档案</button></>:<p>请先导入档案。</p>}</section>}</main>}
